//! # Software Supply Chain Repo Actor State
//!
//! Formalizes repositories as first-class CAR accounts:
//! - Slot 3: Git HEAD (OID) & tree root
//! - Slot 6: Supply Chain Interface Commitment
//! - Note-passing: Upstream interface changes emitted as encrypted notes; nullifier = acceptance.

use alloy_primitives::{Address, B256, Bytes};
use serde::{Deserialize, Serialize};

/// Type of interface modification.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DeltaType {
    /// Non-breaking additive change
    Additive,
    /// Breaking removal of an API or method
    Removing,
    /// Breaking renaming of a type or method
    Renaming,
    /// Breaking type signature modification
    TypeChange,
}

/// Diff of public interface commitments.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InterfaceDelta {
    pub old_commitment: B256,
    pub new_commitment: B256,
    pub delta_type: DeltaType,
    pub summary: Option<String>,
}

/// A repository's supply-chain actor state committed in Slot 3.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RepoActorState {
    /// Current git tree root (OID stored as B256)
    pub git_head: B256,
    /// Branch name (e.g. "main")
    pub branch: String,
    /// Schema commitment: Poseidon/Blake3 hash of repo's public interface contract
    pub interface_commitment: B256,
    /// Epoch of last interface advancement
    pub last_advanced_epoch: u64,
    /// Pinned upstream dependencies: (upstream_repo_address, git_head_at_pin)
    pub pinned_deps: Vec<(Address, B256)>,
}

/// Note payload representing an interface change proposal from an upstream repository.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RepoActorNote {
    /// Upstream repository account address
    pub upstream_repo: Address,
    /// New upstream git HEAD (OID)
    pub new_upstream_head: B256,
    /// Verkle/Merkle witness of the upstream repo's Slot 3 at the new HEAD
    pub slot3_witness: Bytes,
    /// Schema delta of the public interface commitment
    pub interface_delta: InterfaceDelta,
    /// Whether this delta is breaking
    pub is_breaking: bool,
    /// Suggested adapter patch (if auto-generated by upstream agent)
    pub suggested_adapter: Option<Bytes>,
}

/// Decision made by a downstream repo actor upon evaluating an incoming `RepoActorNote`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum RepoActorDecision {
    /// Auto-accepted: non-breaking, tests passed, note nullified, Slot 3/6 advanced
    AutoAccepted { nullifier: B256 },
    /// Auto-adapted: adapter generated, tests passed, note nullified
    AutoAdapted { adapter_commit: B256, nullifier: B256 },
    /// Contention: breaking change requires human review, note remains unspent (open PR)
    Contention { reason: String },
}

/// Evaluates a `RepoActorNote` against the repository state and tests pass boolean.
#[must_use]
pub fn evaluate_repo_actor_note(
    note: &RepoActorNote,
    tests_passed: bool,
    adapter_available: bool,
) -> RepoActorDecision {
    let nullifier = blake3::hash([b"nullifier:", note.new_upstream_head.as_slice()].concat().as_slice());
    let nullifier_b256 = B256::from_slice(nullifier.as_bytes());

    if !note.is_breaking && tests_passed {
        RepoActorDecision::AutoAccepted { nullifier: nullifier_b256 }
    } else if note.is_breaking && adapter_available && tests_passed {
        RepoActorDecision::AutoAdapted {
            adapter_commit: B256::repeat_byte(0x55),
            nullifier: nullifier_b256,
        }
    } else {
        RepoActorDecision::Contention {
            reason: if !tests_passed {
                "Sandboxed CI test matrix failed on incoming commit".to_string()
            } else {
                "Breaking change cannot be automatically resolved without human review".to_string()
            },
        }
    }
}
